import 'dart:io';
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'package:frontend_smart_presence/models/student.dart';
import 'package:frontend_smart_presence/services/student_service.dart';
import 'package:frontend_smart_presence/utils/permissions.dart';

class CSVImporter {
  static Future<List<Student>?> importStudentsFromCSV(
    BuildContext context,
  ) async {
    try {
      // Check storage permission
      final hasPermission = await Permissions.requestStoragePermission();
      if (!hasPermission) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Storage permission is required to import CSV files'),
            backgroundColor: Colors.red,
          ),
        );
        return null;
      }

      // Pick CSV file
      final result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['csv'],
      );

      if (result == null || result.files.isEmpty) {
        // User canceled the picker
        return null;
      }

      final file = File(result.files.single.path!);
      final csvContent = await file.readAsString();

      // Parse CSV content
      final students = _parseCSV(csvContent);

      if (students.isEmpty) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('No valid student data found in CSV file'),
            backgroundColor: Colors.orange,
          ),
        );
        return [];
      }

      // Import students via service
      final studentService = StudentService();
      final importedStudents = await studentService.importStudentsFromCSV(
        csvContent,
      );

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            'Successfully imported ${importedStudents.length} students',
          ),
          backgroundColor: Colors.green,
        ),
      );

      return importedStudents;
    } catch (e) {
      print('Error importing CSV: $e');
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Failed to import CSV: $e'),
          backgroundColor: Colors.red,
        ),
      );
      return null;
    }
  }

  static List<Student> _parseCSV(String csvContent) {
    final lines = csvContent.split('\n');
    final students = <Student>[];

    // Skip header row if present
    bool hasHeader =
        lines.isNotEmpty &&
        (lines[0].contains('name') ||
            lines[0].contains('email') ||
            lines[0].contains('student'));

    final startIndex = hasHeader ? 1 : 0;

    for (int i = startIndex; i < lines.length; i++) {
      final line = lines[i].trim();
      if (line.isEmpty) continue;

      final columns = line.split(',');
      if (columns.length >= 4) {
        // Assuming CSV format: name, email, studentId, className
        final student = Student(
          id: '', // Will be generated by backend
          name: columns[0].trim(),
          email: columns[1].trim(),
          studentId: columns[2].trim(),
          className: columns[3].trim(),
        );
        students.add(student);
      }
    }

    return students;
  }

  static String generateCSVTemplate() {
    return 'name,email,studentId,className\n'
        'John Doe,john.doe@example.com,STU001,Class A\n'
        'Jane Smith,jane.smith@example.com,STU002,Class B\n'
        'Robert Johnson,robert.j@example.com,STU003,Class A';
  }
}
